### ISSUE TITLE
[v1.1.0-alpha1] Unable to require('fb')

### ISSUE THREAD

**Issue by Amoki** [node-facebook/facebook-node-sdk#45]
Hi, 

New features of v1.1 are really interesting but I can't even use the alpha.

When I use the lastest tag on my package.json, I can't require('fb') and get this stack trace:
```js
> var FB =require('fb');
Error: Cannot find module 'fb'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at repl:1:9
    at REPLServer.defaultEval (repl.js:269:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:439:12)
    at emitOne (events.js:95:20)
```

I'm using node v 5.10.1 and npm 3.8.3

**Steps to reproduce**
```sh
mkdir /tmp/test
cd /tmp/test
npm install node-facebook/facebook-node-sdk.git#v1.1.0-alpha1
node
> var FB = require('fb');
```
Note: It is the same with master.

Thank you for maintaining such a good library!

**Comment by dantman** [comment]
Don't depend on the git repo, the repository doesn't contain the compiled sources.

Use `npm install fb@^1.1.0-alpha1`.
